### ISSUE TITLE
1.04 Noclip Bugs Out

### ISSUE THREAD

**Issue by juraisa** [hoiblij/cyberpunknoclip#2]
the flight keys are working fine, but enabling Noclip on 1.04 GOG atleast causes your character to start moving all over the place on it's own sporadically until you turn it off again

**Comment by hoiblij** [comment]
Updated for 1.04

**Comment by juraisa** [comment]
Thanks hoiblij

**Comment by Brandomanmods** [comment]
Seems this issue is still present.  I'll be floating around trying to find a good position to record but then all of a sudden it loads into a random position in the map.  One time it set me over 20 miles away from the map.  There is also a slow drop in the camera when in the air.  I want to stand still to make some timelapse videos from different angles.
